### ISSUE TITLE
JSStreamSocket hack not compatible with bun

### ISSUE THREAD

**Issue by jedrichards** [szmarczak/http2-wrapper#109]
The code here, reaching into some internal properties:

https://github.com/szmarczak/http2-wrapper/blob/f1a1776d4b1aef1cd47d55b1a950986e86145a09/source/utils/js-stream-socket.js#L6

Seems to be incompatible with `bun`, and triggers the following crash:

```
TypeError: null is not an object (evaluating 'new tls.TLSSocket(new stream.PassThrough)._handle._parentWrap')
```

**Comment by Deyvan** [comment]
I think it's has already been fixed
https://github.com/oven-sh/bun/commit/c04a2d1dfc6daa64e4e45175ae69f1659669e6a5

**Comment by jedrichards** [comment]
Ah all good then - thanks for the link 😌
