### ISSUE TITLE
TypeScript typings

### ISSUE THREAD

**Issue by szmarczak** [szmarczak/http2-wrapper#26]

**Comment by callmehiphop** [comment]
Do you want to convert the lib to TypeScript or just include declaration files with all the typings?

**Comment by szmarczak** [comment]
I think just the declaration files for now.

The code still may change drastically, so let's wait until Got integrates with the wrapper first before rewriting this in TypeScript.

**Comment by szmarczak** [comment]
I have done some basic [types](https://github.com/szmarczak/http2-wrapper/blob/master/index.d.ts). I just need to [test](https://github.com/szmarczak/cacheable-lookup/blob/master/index.test-d.ts) them using [tsd](https://github.com/SamVerschueren/tsd).

**Comment by szmarczak** [comment]
Ok, so I've finished the tests. The coverage has reached 100% :tada: I'll do the typings tomorrow, then update the docs, then make a `1.0.0` release.

**Comment by szmarczak** [comment]
Just finished the types. I just need to test them and update the docs.

**Comment by szmarczak** [comment]
Did most of them here: 5f11221f2b7c9b3f281d0ec91842fa33d1537546

### TODO

- [ ] Test proxy typings
- [ ] Update docs
- [ ] Release `http2-wrapper@1.0.0`
