### ISSUE TITLE
HTTP(s) Proxy CONNECT support

### ISSUE THREAD

**Issue by corford** [szmarczak/http2-wrapper#40]
With previous versions of Got, I've relied on https://github.com/TooTallNate/node-https-proxy-agent for proxy support.

Are there any plans to add similar CONNECT support to http2-wrapper so h2 requests can go through a proxy?

**Comment by szmarczak** [comment]
It's currently possible to do so. You just need to overwrite `agent.createConnection` and `agent.request`. Please note that it requires to write your own proxy server.

I'll make one and put it in the `examples` directory.

Reference: https://nodejs.org/api/http2.html#http2_supporting_the_connect_method

**Comment by corford** [comment]
Thanks for replying so quickly. So, if I've understood correctly, that takes care of proxying native h2 connections (which is great!).

Once HTTP2 is enabled by default in Got v12, what would be the approach for re-using an existing https proxy connection after an ALPN protocol upgrade has happened?

**Comment by szmarczak** [comment]
> what would be the approach for re-using an existing https/tls proxy connection after an ALPN protocol upgrade has happened?

Agents do it automatically. Do you mean you want to push your own socket instance into your Agent?

> situations where you need to proxy outbound connections

You can make your server turn your HTTP/2 requests into HTTP/1 if the destination doesn't support HTTP/2. That way all the proxied requests would go to your HTTP/2 proxy server. The benefit is that you'd have only one connection to the proxy and infinite amount of requests (in HTTP/2 it's called `streams`).

**Comment by corford** [comment]
>You can make your server turn your HTTP/2 requests into HTTP/1 if the destination doesn't support HTTP/2. That way all the proxied requests would go to your HTTP/2 proxy server. The benefit is that you'd have only one connection to the proxy and infinite amount of requests (in HTTP/2 it's called streams).

I guess this is what I mean but at the client/agent level rather than the proxy server (which let's assume is out of our control and doesn't speak h2 natively).

The flow as I understand it would be:

1. Agent establishes socket to proxy server (with CONNECT header specifying `https://nghttp2.org/httpbin/anything` as Origin)

2. Agent performs TLS handshake with Origin (through the now established socket with proxy server) and advertises h2 support via ALPN.

3. Origin and Agent both upgrade to h2.

4. Agent then swaps to using HTTP/2.0 streams for communicating with the Origin (all through the underlying TLS socket to the proxy server)

Probably I'm confused about the role `http2-wrapper` is playing in all this. I assumed for the above scenario (passing Got requests though a non-h2 aware proxy server), http2-wrapper would need to be able to handle the initial socket and CONNECT setup with the proxy server (as seen with e.g. https://github.com/TooTallNate/node-https-proxy-agent ) ?

**Comment by szmarczak** [comment]
> I guess this is what I mean but at the client/agent level rather than the proxy server (which let's assume is out of our control and doesn't speak h2 natively).

Unfortunately that's not possible at the agent level. Agents are per protocol. They don't do ALPN negotiation. I think you're looking for `http2.auto`. It does ALPN negotation and lets you provide different agents for different protocols. But that's already included in Got.

**Comment by corford** [comment]
Ok, that makes sense - thanks!

So if `http2.auto` takes care of the low-level TCP connection and ALPN, what is the recommended way to configure it to go through a non-h2 aware proxy server (and ensure subsequent HTTP/2.0 requests/streams made by Got pass down this socket)?

https://github.com/sindresorhus/got#proxies mentions specifying a `tunnel` agent but I'm not sure that's valid for Got v11+ (since `agent` is now expected to be an object with http ,https and http2 props).

**Comment by szmarczak** [comment]
> I'm not sure that's valid for Got v11+ (since agent is now expected to be an object with http, https and http2 props).

Good find! Please make an issue about this.

> Or is it sufficient to simply specify tunnel for the https agent property and then Got will automatically use that for HTTP/2.0 traffic (after successful ALPN negotiation)?

No, you need to provide **both**: https & http2.

**Comment by corford** [comment]
>Good find! Please make an issue about this.
I'll make one now (and move discussion to there since I think what I'm asking is more related to Got rather than http2-wrapper)

**Comment by corford** [comment]
Looking at the source of Got and http2-wrapper, it appears the current way to do it would be by passing a pre-created socket via `createConnection()` ? An issue I can see is that this would prevent socket re-use during after `resolveProtocol()` completes.

**Comment by szmarczak** [comment]
Released `1.0.0-beta.5.2` which now supports proxying. See the readme file.
