### ISSUE TITLE
to Add support for keepalive option for HTTP2.request

### ISSUE THREAD

**Issue by masx200** [szmarczak/http2-wrapper#41]
to Add support for keepalive option for HTTP2.request

In a period of time, if you initiate multiple requests to the same server, you can reuse the same http2 session.

```js
const http2 = require('http2-wrapper');

const options = {
keepAlive:true,
	hostname: 'nghttp2.org',
	protocol: 'https:',
	path: '/httpbin/post',
	method: 'POST',
	headers: {
		'content-length': 6
	}
};
const timer=setInterval(()=>{
const request = http2.request(options, response => {})

},1000)
```

**Comment by szmarczak** [comment]
HTTP2 is a different protocol than HTTP1. You cannot disable keep alive here.

**Comment by LucasianProfessor** [comment]
What about when I use

`const agent = new http2.proxies.Http2OverHttp({
				proxyOptions: {
					keepAlive: true,
					url: proxystring,
					rejectUnauthorized: false
				}
			});`

as an Agent instead? Does keep-Alive work despite being routed over http/1.1 proxy ?
