### ISSUE TITLE
Proxy Error

### ISSUE THREAD

**Issue by yovanoc** [szmarczak/http2-wrapper#43]
I tried this example https://github.com/szmarczak/http2-wrapper/blob/master/examples/proxy/h2-over-h2.js
and I got this error.

```
(node:77358) UnhandledPromiseRejectionWarning: Error: Session closed without receiving a SETTINGS frame
    at ClientHttp2Session.<anonymous> (/Users/devchris/Desktop/project/node_modules/http2-wrapper/source/agent.js:396:22)
    at Object.onceWrapper (events.js:420:28)
    at ClientHttp2Session.emit (events.js:314:20)
    at ClientHttp2Session.EventEmitter.emit (domain.js:486:12)
    at emitClose (internal/http2/core.js:999:8)
    at internal/http2/core.js:1036:7
    at TLSSocket.onfinish (_stream_writable.js:677:5)
    at TLSSocket.emit (events.js:314:20)
    at TLSSocket.EventEmitter.emit (domain.js:486:12)
    at finish (_stream_writable.js:645:10)
```

I thought it was the proxy that doesn't support http2 but the provider tells me that the proxy actually supports it.

What do you think?

Thanks

**Comment by szmarczak** [comment]
Maybe you're looking for http/1 over http/2? Are you sure it's http/2 over http/2?

**Comment by szmarczak** [comment]
May I know who's the proxy provider?

**Comment by szmarczak** [comment]
How often do you see the error?

**Comment by yovanoc** [comment]
https://buyproxies.org

I see this error for each request :/

And no I really want to access the final server with http2 (because there are some cloudflare rules xD)

**Comment by yovanoc** [comment]
But simple question: in your exemple we can add credentials like that right?

```
agent: new ProxyAgent('https://username:password@ip:port'),
```

?

**Comment by szmarczak** [comment]
Not yet :P You need to pass the `proxy-authorization` header manually for now.

**Comment by szmarczak** [comment]
Try adding `proxy-authorization` entry right after this one: https://github.com/szmarczak/http2-wrapper/blob/0fd01089f3dc119929aedcdd5e3751c867fee14d/examples/proxy/h2-over-h2.js#L16

**Comment by yovanoc** [comment]
```ts
return super.request(
      this._origin,
      sessionOptions,
      {
        ...headers,
        ":authority": url.host,
        "Proxy-Authorization": `Basic ${Buffer.from("username:password").toString(
          "base64"
        )}`
      },
      streamOptions
    );
```

(with real credentials of course)

and still the same but ty for that information too

**Comment by szmarczak** [comment]
Can you try the `h1-over-h2` example?

Where can I find the info that the proxy supports HTTP/2?

**Comment by yovanoc** [comment]
Oh I think about an important note here. I use this agent in got. I add http2: true, and agent: { http2: new ProxyAgent(...) }.

but yes i will try

**Comment by yovanoc** [comment]
And the information is a mail exchange, not directly on the website :/

**Comment by szmarczak** [comment]
Can you try `h1-over-h2`? Just set `http2` to `false` and pass the `createConnection` option.

**Comment by yovanoc** [comment]
there is no http2-wrapper involved in your h1-over-h2 example?

I tried it (but without proxy-authorization, i don't know how to put this) and I get

```
Error: socket hang up
    at connResetException (internal/errors.js:613:14)
    at ClientHttp2Stream.socketOnEnd (_http_client.js:493:23)
    at ClientHttp2Stream.emit (events.js:314:20)
    at ClientHttp2Stream.EventEmitter.emit (domain.js:486:12)
    at endReadableNT (_stream_readable.js:1226:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
error Command failed with exit code 1.
```

**Comment by szmarczak** [comment]
> there is no http2-wrapper involved in your h1-over-h2 example?

I haven't written an Agent for this yet. `createConnection` should be OK.

> but without proxy-authorization

The entry should be placed right after this line: https://github.com/szmarczak/http2-wrapper/blob/0fd01089f3dc119929aedcdd5e3751c867fee14d/examples/proxy/h1-over-h2.js#L16

**Comment by yovanoc** [comment]
yes a simple createConnection without proxy it works

**Comment by yovanoc** [comment]
and a h2-over-h1 would not be possible?

**Comment by szmarczak** [comment]
> yes a simple createConnection without proxy it works

What do you mean? The request isn't proxied when using createConnection?

**Comment by szmarczak** [comment]
> and a h2-over-h1 would not be possible?

No, because h1 uses TCP and h2 uses QUIC I think...

**Comment by yovanoc** [comment]
Ohhhh I thouht you was speaking about that

```ts
export class Http2ProxyAgent extends http2.Agent {
  private _origin: string;

  constructor(url: string, options?: unknown) {
    super(options);

    this._origin = url;
    console.log(this._origin);
  }

  createConnection(
    origin: URL,
    options: SecureClientSessionOptions
  ): TLSSocket {
    console.log(`Connecting to ${http2.Agent.normalizeOrigin(origin)}`);
    return http2.Agent.connect(origin, options);
  }
}
```

But yeah if by createConnection you speak about the h1-over-h2 example I got the previous `socket hang up` error even with the Proxy-Authorization header

**Comment by yovanoc** [comment]
PS: for proxying I just add this method to the Http2ProxyAgent

```ts
async request(
    origin: string | URL,
    sessionOptions?: SecureClientSessionOptions,
    headers?: OutgoingHttpHeaders,
    streamOptions?: ClientSessionRequestOptions
  ): Promise<ClientHttp2Stream> {
    const url = typeof origin === "string" ? new URL(origin) : origin;

    return super.request(
      this._origin,
      sessionOptions,
      {
        ...headers,
        ":authority": url.host,
        "Proxy-Authorization": `Basic ${Buffer.from("username:password").toString(
          "base64"
        )}`
      },
      streamOptions
    );
  }
```

**Comment by szmarczak** [comment]
I don't think they support the CONNECT protocol. Can you try https://github.com/szmarczak/http2-wrapper#classic-web-proxy ?

**Comment by szmarczak** [comment]
Also if you have succeded with the native `http` Agent, can you share the code how did you do it? Is there any specific library for this? Is it a SOCKS proxy?

**Comment by yovanoc** [comment]
With Got if I replace http2: true by false, and agent: { http2: xxx } by https with the node-https-proxy-agent library all is working but I have to use http2 to bypass a cloudflare rule for my desired endpoint

**Comment by yovanoc** [comment]
https://gist.github.com/yovanoc/0bb782133f8eb363a45feea891ded0e4

here my test too, doesn't work

**Comment by yovanoc** [comment]
But QUIC is for h3 not h2 so it may be possible

**Comment by szmarczak** [comment]
> But QUIC is for h3 not h2 so it may be possible

Hmm, you're right. I tried creating a session on top of a stream but that failed for some reason. I haven't dug deeper why.

**Comment by szmarczak** [comment]
I have updated the H1overH2 example to use `Agent` instead of the `createConnection` option: https://github.com/szmarczak/http2-wrapper/#http1-over-http2

I will try to create a HTTP/2 session on top of a HTTP/2 again later today.

**Comment by yovanoc** [comment]
Oh nice but I was speaking about h2 over h1 ^^

**Comment by szmarczak** [comment]
Sure, I will check that out too...

**Comment by yovanoc** [comment]
Oh sorry i didn't want to rush you! thank you for all this amazing work!

**Comment by szmarczak** [comment]
I've done [massive](https://github.com/szmarczak/http2-wrapper/commit/21940a0d5f7f220b593d12d8b3c67bde5ffd9a3e) changes to the code. Also I've fixed a [Node.js](https://github.com/szmarczak/http2-wrapper/commit/21940a0d5f7f220b593d12d8b3c67bde5ffd9a3e#diff-7e2e946db51a4f98c2aa3bd58b5eb94aR632-R637) resulting in incorrect Origin Set which caused infinite loop in some scenarios. What's more, finally I added full URL `https://username:password@host:port/path` support. There's no release yet, but please do test the code from the master branch and do let me know if it works for you or not.

**Comment by yovanoc** [comment]
Hi, 

First I've found this error

`[ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "proxy-authorization"`

that we can fix with a thing like this in the h2-over-h1

```js
headers: this.proxyOptions.authorization ? {
				...this.proxyOptions.headers,
				'proxy-authorization': this.proxyOptions.authorization
			} : this.proxyOptions.headers,
```


But no all of the example, with my proxy provider and for some free proxy without auth found on google (with the same httpbin endpoint, I just changed the url each time and try to make some tweaks with your comments) does not work.

I get `Session closed without receiving a SETTINGS frame` or `UnexpectedStatusCodeError: The proxy server rejected the request with status code 503` with 502 or 503

**Comment by szmarczak** [comment]
[So I did some polishing](https://github.com/szmarczak/http2-wrapper/compare/21940a0d5f7f220b593d12d8b3c67bde5ffd9a3e...master). You can run the servers locally and test it on your own :) If it doesn't work with other servers then they aren't compatible.

> [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "proxy-authorization"

Fixed.

- `Session closed without receiving a SETTINGS frame` simply means that the server didn't want to connect with us and rejected the session.
- `UnexpectedStatusCodeError: The proxy server rejected the request with status code 503` means the proxy is full and won't make a request for us.
- `wrong version number` means the server sent decrypted TLS data instead of the encrypted ones
- `UnexpectedStatusCodeError: The proxy server rejected the request with status code 403` means you're not authorized.

Hope everything's clear now. I'm closing this for now. If you have any other questions, don't hesitate to ask.

**Comment by younes-zeboudj** [comment]
Interesting discussion ... Thank you for the efforts @szmarczak 
@yovanoc I find your use case similar to mine, did you arrive to query the cloudflare protected url using http2 while using a proxy?
