### ISSUE TITLE
Add tests for proxies

### ISSUE THREAD

**Issue by szmarczak** [szmarczak/http2-wrapper#44]
TODO before writing tests:

- [x] Make the constructor of `Http2OverHttpX` use the common `initialize` function
- [x] `getSession()` should create new proxy stream ONLY when needed, not on every call!
- [x] Rethink the structure of `this.queue` and `this.sessions`

**Comment by szmarczak** [comment]
So after bab638bb8ee8bb224e1a3e4b9e4ab87c30268728 many tests will fail because the internal API has changed a bit. Will fix this later.

**Comment by szmarczak** [comment]
Also let's consider using `WeakMap` instead of `session[symbolHere]`

**Comment by Revadike** [comment]
How come `http2.proxies` is `undefined` for me?

**Comment by szmarczak** [comment]
This project is still WIP. Please wait for a 1.0 release.

**Comment by Revadike** [comment]
I have great interest in it, since I need access to a website that only accepts http2 and I need proxy support. Other proxy solutions failed me.

**Comment by Revadike** [comment]
I've been trying several versions, without success. Any version you currently recommend for a best chance of having http2 proxy support working (for node-got)?

**Comment by szmarczak** [comment]
https://github.com/szmarczak/http2-wrapper/issues/44#issuecomment-768309938

**Comment by szmarczak** [comment]
100% https://codecov.io/gh/szmarczak/http2-wrapper

**Comment by Revadike** [comment]
Awesome dude. When may we expect the new version?

**Comment by szmarczak** [comment]
Definitely next week

**Comment by Revadike** [comment]
I'm getting `RequestError: The "options.agent" property must be one of Agent-like Object, undefined, or false. Received an instance of Http2OverHttp` when trying to use the agent (version = current github repo) with `got`.

**Comment by Revadike** [comment]
Could you please explain how I can make a http2 request with `got` using a http proxy?

**Comment by Revadike** [comment]
I'm even running into problems with using `got`. I'm running your test/example code with my proxy service to `https://bot.whatismyipaddress.com` and I'm getting 407. Why am I not properly authenticated? I'm using `new URL("http://user:password@domain.com")`

```js
"use strict";
const http2 = require("http2-wrapper"); 

const agent = new http2.proxies.Http2OverHttp({
    "proxyOptions": {
        "url": new URL(`http://customer- ... : ... @ ... .oxylabs.io: ...`),

        // For demo purposes only!
        "rejectUnauthorized": false,
        // "raw":                  false,
        // "headers":              {
        //     "alpn-protocols": "h2"
        // }
    }
});

const request = http2.request("https://bot.whatismyipaddress.com", {
    agent
}, response => {
    console.log("statusCode:", response.statusCode);
    console.log("headers:", response.headers);

    const body = [];
    response.on("data", chunk => {
        body.push(chunk);
    });
    response.on("end", () => {
        console.log("body:", Buffer.concat(body).toString());
    });
});

request.on("error", console.error);

request.end();
```
