### ISSUE TITLE
Don't use H2 detection preflights & caching in Node versions where it's not required

### ISSUE THREAD

**Issue by pimterry** [szmarczak/http2-wrapper#49]
As far as I can tell, the TLS preflight requests and detected protocol caching in https://github.com/szmarczak/http2-wrapper/blob/master/source/auto.js exists purely because of https://github.com/nodejs/node/issues/33343. Is that right?

This bug doesn't exist in many of the recent Node versions (e.g. in my case I'm using Node 14.6). It would be nice to skip all that logic in those cases. That has two main benefits:

* Saves a duplicate TLS handshake and the associated RTT for the first connections to each host and for hosts that fall out of the cache.
* No cache invalidation issues. In my case, my tests just started failing because they reuse a port for some test servers, not all of which have the same H2 configuration, so cached initial values broke later requests.
* Simplifies the code in those cases, and starts towards a path where this can be dropped completely and simplify the code fully (although I know that can't happen any time soon).

I've added some notes on the node issue about the fix. I think this is unnecessary from Node 14.3+, and I'm hopeful we can get it sorted in an v12 release sometime soon too. What do you think?

**Comment by szmarczak** [comment]
> Is that right?

If you mean

https://github.com/szmarczak/http2-wrapper/blob/10ee5ffb9e201b786766aa9b45ed988a569c20ae/source/auto.js#L63-L64

then yes.

> Saves a duplicate TLS handshake and the associated RTT for the first connections to each host and for hosts that fall out of the cache.

If you know that the server supports HTTP/2 then there's no point in using `http2.auto`.

> No cache invalidation issues. In my case, my tests just started failing because they reuse a port for some test servers, not all of which have the same H2 configuration, so cached initial values broke later requests.

That's not possible. Agent creates a new session on every option change:

https://github.com/szmarczak/http2-wrapper/blob/10ee5ffb9e201b786766aa9b45ed988a569c20ae/source/agent.js#L12-L45

**Comment by pimterry** [comment]
> If you know that the server supports HTTP/2 then there's no point in using http2.auto.

I don't know in advance if the server supports HTTP/2, and I do need `http2.auto`.

In the case where you use `auto` and it does happen to support HTTP/2 though, http2-wrapper currently requires two TLS handshakes for the first connection, right?

With this bug fixed, that's not strictly necessary. We could do a single TLS handshake, and then decide whether to do HTTP/1 or HTTP/2 afterwards, without creating a new socket, similar to what the HTTP/1 HTTPS connections already do with [`installSocket`](https://github.com/szmarczak/http2-wrapper/blob/10ee5ffb9e201b786766aa9b45ed988a569c20ae/source/auto.js#L13-L38).

This isn't a big problem, but it does seem a bit wasteful to make the connection twice if we don't need to.

> That's not possible. Agent creates a new session on every option change

In my case the options aren't changed. I make exactly the same request, and in some tests it goes to an H1-only server, and in some tests it goes to an H2-only server. With http2-wrapper that second request fails.

This is because I have different tests that use many different mock servers, but which often share the exact same URL (because they're test servers, and they just use the first localhost port that's free).

**Comment by szmarczak** [comment]
> in some tests it goes to an H1-only server, and in some tests it goes to an H2-only server. With http2-wrapper that second request fails.

```js
http2wrapper.auto.protocolCache.clear();
```

> http2-wrapper currently requires two TLS handshakes for the first connection, right?

Yes, this will be fixed in an upcoming release.

**Comment by pimterry** [comment]
> `http2wrapper.auto.protocolCache.clear();`

Neat, that's definitely helpful, thanks :+1:.

> Yes, this will be fixed in an upcoming release.

Ok, amazing! That's what I'm proposing really, great to hear that that's planned. Are there details anywhere on how that'll work? Will it work for Node < 14.3 too?

**Comment by szmarczak** [comment]
> Are there details anywhere on how that'll work?

I haven't looked deeper into this.

**Comment by pimterry** [comment]
Fair enough. Let me know if there's anything I can do to help.

**Comment by szmarczak** [comment]
Done 27d437a9f9ccb1c252eb7aeed61bccd1dafccc5e although there are still some things to address:

- some of the code should be moved to https://github.com/szmarczak/resolve-alpn
- before a new release is published, some parts of `http2.Agent` need to be rebased.

**Comment by szmarczak** [comment]
If I have the time then I'll do another beta release (so many of them already! :P) this weekend.

**Comment by pimterry** [comment]
Amazing, thanks! Definitely looking forward to the next release, great work :+1:

**Comment by szmarczak** [comment]
Actually I'm not sure if it's be possible to reuse TLS sockets for HTTP/2. See https://github.com/nodejs/node/issues/35475

**Comment by szmarczak** [comment]
https://github.com/nodejs/node/commit/75202d971d3a18824f357bbb31671291a1dc4e84 we just need to wait for an actual release

**Comment by szmarczak** [comment]
Node.js v15.1.0 got just released, it should be possible to fix this issue now.

**Comment by szmarczak** [comment]
Meh, https://github.com/nodejs/node/issues/35981

**Comment by szmarczak** [comment]
Node.js v15.3.0 was released yesterday, I'll try to fix this ASAP.

**Comment by szmarczak** [comment]
Fixed on master. Node.js v15.3.0 is required for HTTP/2 socket reuse.

I'll try to make a release this weekend.

**Comment by szmarczak** [comment]
I still keep finding new Node.js bugs hehe :P https://github.com/nodejs/node/issues/34854
