### ISSUE TITLE
Don't wait for 'finish' before 'response'

### ISSUE THREAD

**Issue by pimterry** [szmarczak/http2-wrapper#51]
H2 client requests wait for the request body writing to finish before they fire `response` events (or `headers` or `trailers` events):

https://github.com/szmarczak/http2-wrapper/blob/10ee5ffb9e201b786766aa9b45ed988a569c20ae/source/client-request.js#L252-L267

(Implemented in https://github.com/szmarczak/http2-wrapper/commit/2d6279a36f501daab96990867cf5164ad6f0f6ee, apparently for proxying purposes).

This doesn't match Node's HTTP/1 behaviour, and that's breaking my application. Servers can respond before the body for all sorts of reasons, like rejecting uploads before the body is completed. In my case, I'm proxying mixed HTTP/1 & HTTP/2 traffic, and some of that traffic talks to Google's firebase API, which does some interesting two-way communication by reading & writing response bodies, and _requires_ clients to receive response headers before the request is fully completed.

Here's a pure HTTP/1 example where `response` fires without `finish`:

```javascript
const http = require('http');

const server = http.createServer((req, res) => {
    console.log('got request');

    // Don't wait for the full body - reply immediately:
    res.writeHead(200);
    res.flushHeaders(); // .end() also works, but stops the request completely
});

server.listen(5050, () => {
    const req = http.request('http://localhost:5050', {
        method: 'POST'
    });

    req.on('response', (res) => console.log('response:', res.statusCode));
    req.on('finish', () => console.log('req finished'));

    req.write('start writing');
    setTimeout(() => {
        console.log('end');
        req.end('end');
    }, 100);
});
```

It outputs:

```
got request
response: 200
end
req finished
```

You can fix this very easily by just removing `waitForEnd`, but based on [the original commit](https://github.com/szmarczak/http2-wrapper/commit/2d6279a36f501daab96990867cf5164ad6f0f6ee) that presumably breaks something related to proxying? I'm not sure about the details of that, but in my application with that change it all seems to work great.

**Comment by pimterry** [comment]
@szmarczak any thoughts on this? I'm fairly sure it's incorrect behaviour, and it'll plausibly cause problems in other downstream projects. It breaks any API where the server is expected to reply without waiting for the request body, including popular APIs like Firebase.

**Comment by szmarczak** [comment]
Hey, sorry for delay. I'll dig deeper into this and see why I decided to wait for the `finish` event. Indeed, this is a bug.

**Comment by szmarczak** [comment]
This is a bit related to `http2-proxy`. I'm fixing this right now.

**Comment by szmarczak** [comment]
Also your issue led to a another bug:

```js
test.only('the `response` event can be emitted after calling `request.write()`', wrapper, async (t, server) => {
	server.post('/', (request, response) => {
		request.resume();
		response.end();
	});

	const request = makeRequest({
		...server.options,
		method: 'POST'
	});
	request.write('anything');

	const response = await pEvent(request, 'response');
	t.is(response.statusCode, 200);

	request.end();
});
```

gives

```js
  Uncaught exception in test/request.js

  Error [ERR_STREAM_DESTROYED]: Cannot call end after a stream was destroyed

  › callEnd (source/client-request.js:193:18)
  › ClientRequest._final (source/client-request.js:197:4)
```

**Comment by pimterry** [comment]
@szmarczak would it be possible to cut another beta release sometime soon? Having this fix available would be really useful.

**Comment by szmarczak** [comment]
I'll do tomorrow
