### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by szmarczak** [szmarczak/http2-wrapper#56]
Should we go with semantic versioning or mirror Node.js versions? E.g. if we know that the current state is fully compatible with `14.11.0`, release `@szmarczak/http2-wrapper@14.11.0`. DefinitelyTyped does this with `@types/node`.

/cc @sindresorhus

**Comment by sindresorhus** [comment]
I think it should keep its own versioning. Suddenly you need to do a breaking change not related to Node.js and then it becomes out of sync. You could have a table to document what `http2-wrapper` versions are compatible with what Node.js versions.
