### ISSUE TITLE
H2-over-H1 Proxy question

### ISSUE THREAD

**Issue by wuyansongs** [szmarczak/http2-wrapper#57]
Run the example code h2-over-h1.js

Result:

`Error: Requested origin https://httpbin.org does not match server https://httpbin.org:8765`

> `at ClientHttp2Session.<anonymous> (/home/chandler/projects/seckill/http2-wrapper/source/agent.js:535:22)`

> `at Object.onceWrapper (events.js:422:26)`

> `at ClientHttp2Session.emit (events.js:315:20)`

> `at Http2Session.onSettings (internal/http2/core.js:536:11) {stack: 'Error: Requested origin https://httpbin.org d…on.onSettings (internal/http2/core.js:536:11)', message: 'Requested origin https://httpbin.org does not match server https://httpbin.org:8765'}
`

the port 8765 is Charles Proxy port

**Comment by szmarczak** [comment]
Hi, currently I don't recommend running HTTP/2 as I don't think it's stable enough: https://github.com/nodejs/node/issues/36289

I'll resume working on this once they fix the issue above.
