### ISSUE TITLE
Make proxies in source available in NPM package

### ISSUE THREAD

**Issue by andrisi** [szmarczak/http2-wrapper#62]
Would be great to have the proxy examples (classes) available in the NPM package so no mingling with the source distribution would be required - and perhaps get to got dosc to efer to this. Or is it there already somehow? Thanks a lot.

https://github.com/szmarczak/http2-wrapper/#proxy-support

**Comment by szmarczak** [comment]
#26

**Comment by szmarczak** [comment]
I'll make a `1.0.0` in the next few days.
