### ISSUE TITLE
Node.js 15 breaking homebridge-ring

### ISSUE THREAD

**Issue by MeatAssassin** [szmarczak/http2-wrapper#65]
After installing the update release today, homebridge-ring stopped working per https://github.com/dgreif/ring/issues/577

I saw that Node.js 15 was required which made things even worse.  Homebridge and homebridge-ring only support even numbered Node.js releases.  It might be better to only require that latest Latest Version which is 14.16.0 .  Version 15 is kind of only for early adopters.  The odd numbered releases tend to introduce new features that break other plugins.

Thanks for looking into this....

Todd

**Comment by MeatAssassin** [comment]
More references : https://github.com/dgreif/ring/issues/507

**Comment by MeatAssassin** [comment]
https://github.com/homebridge/homebridge/wiki/How-To-Update-Node.js

**Comment by szmarczak** [comment]
Re-released the beta version as `1.0.3`. The problems should be gone now. Do let me know.
