### ISSUE TITLE
Socket from the real host is used despite proxy if ALPN negotiation occurs

### ISSUE THREAD

**Issue by szmarczak** [szmarczak/http2-wrapper#75]
The socket from the real host is used instead.

/cc @mnmkng

**Comment by szmarczak** [comment]
Actually this issue is wrong. No such thing happens.

**Comment by mnmkng** [comment]
Does this mean that the IP does not leak with the TCP connection or does this just mean that the socket is not reused for the actual requests?

**Comment by szmarczak** [comment]
The socket is not reused but it still leaks the IP address. It connects to the server to get the protocol via real IP then drops the connection and makes a new one with the proxy.
