### ISSUE TITLE
Type definitions (re)broken in 2.0.8

### ISSUE THREAD

**Issue by pimterry** [szmarczak/http2-wrapper#76]
The TypeScript definitions were changed in https://github.com/szmarczak/http2-wrapper/commit/40292c6817f024966185512aad23977fc5e8082b to include:

```typescript
import QuickLRU from 'quick-lru';
```

This breaks all TypeScript usage of this library if `esModuleInterop` is not enabled, with:

> node_modules/http2-wrapper/index.d.ts(9,8): error TS1259: Module '"/.../node_modules/quick-lru/index"' can only be default-imported using the 'esModuleInterop' flag

It looks like this was previously [fixed](https://github.com/szmarczak/http2-wrapper/commit/86bf5cdd184cd37bdaa2a70d84efd7a7c645cc2b) in 2.0.7 for all the imports in the type definitions, but this one import has since been reverted by accident.

**Comment by szmarczak** [comment]
Thanks, released `2.1.1`.

**Comment by pimterry** [comment]
Super fast! Thanks :+1:
