### ISSUE TITLE
Not compatible with version nodejs lts 14

### ISSUE THREAD

**Issue by ngalia** [szmarczak/http2-wrapper#78]
Hello,
The library is incompatible with nodejs 14 (current lts version), because if we use a proxy in http2 we have a problem with the urlToHttpOptions which does not exist in versions lower than 15.
 https://nodejs.org/docs/latest-v14.x/api/url.html

Could you fix the urlToHttpOptions in the auto.js, in the previous versions 1.0.0 you used an internal code for the urlToHttpOptions, could you put this code in the case where the urlToHttpOptions is undefined, at least your library will be compatible with the lts of nodejs?

Thanks in advance,

**Comment by szmarczak** [comment]
Sorry, older versions are too buggy. Upgrade your Node.js version.

**Comment by szmarczak** [comment]
Also see https://github.com/szmarczak/http2-wrapper/issues/73#issuecomment-878502661
