### ISSUE TITLE
url.urlToHttpOptions(url) is not a function

### ISSUE THREAD

**Issue by barjin** [szmarczak/http2-wrapper#81]
url.urlToHttpOptions has been [added in _v15.7.0_](https://nodejs.org/api/url.html#url_url_urltohttpoptions_url). 

In this project's [package.json](https://github.com/szmarczak/http2-wrapper/blob/master/package.json), in the "engines" field, the minimal version of node is said to be _10.19.0_. 

Using this module with lower versions of node (e.g. LTS 14.x.x) leads to an exception getting thrown (aforementioned function called from [/source/auto.js](https://github.com/szmarczak/http2-wrapper/blob/master/source/auto.js)).

**Comment by szmarczak** [comment]
Duplicate of #73
