### ISSUE TITLE
feature request: keep track of bandwidth usage

### ISSUE THREAD

**Issue by andrisi** [szmarczak/http2-wrapper#87]
Would be great to get the current total bandwidth usage of this component. So as I do requests through got for example, I could see how much proxy bandwidth I used up. Thanks!

**Comment by andrisi** [comment]
@szmarczak any chance you could have a look at this and decide if you'd consider discussing it? Thanks!

**Comment by szmarczak** [comment]
Do you mean just HTTP/2 or both HTTP/2 and HTTP/1 requests?

**Comment by andrisi** [comment]
Thanks for getting back to me. I mainly use HTTP/2, so for me that would help a lot, but I guess it would be a useful feature in general, as if you're using a metered proxy connection, it's good to know how much you "spend".

**Comment by szmarczak** [comment]
This is quite problematic, because the socket is unassigned when the session is closed. Node.js' idea is that you can't modify the socket, so probably that's why.

```js
const http2 = require('http2');

const session = http2.connect('https://example.com');

session.once('close', () => {
    console.log(Boolean(session.socket)); // false
});

session.once('remoteSettings', () => {
    // However this works
    session.socket.once('close', function() {
        console.log(this.bytesRead);
    });

    session.close();
});
```

**Comment by szmarczak** [comment]
I think you might be looking for https://nodejs.org/api/perf_hooks.html#http2-http2-details

**Comment by szmarczak** [comment]
Ref: https://github.com/nodejs/node/issues/22268

**Comment by andrisi** [comment]
thanks @szmarczak
