### ISSUE TITLE
resolve-alpn

### ISSUE THREAD

**Issue by ddo** [szmarczak/http2-wrapper#9]
``resolve-alpn`` should be installed as dependencies not dev one

**Comment by nwoltman** [comment]
@szmarczak The current published version of `http2-wrapper` (`0.4.2`) can't run because of this bug.

```
> node -e "require('http2-wrapper')"
internal/modules/cjs/loader.js:626
    throw err;
    ^

Error: Cannot find module 'resolve-alpn'
```

Could you possibly publish a new version with the fix?

**Comment by szmarczak** [comment]
@nwoltman The master branch is almost stable now, but I need to finish the tests though. And as much I would love to, the last few weeks I've been busy with two school competitions. `npm install resolve-alpn` should fix the error.

**Comment by nwoltman** [comment]
Okay no worries!

> `npm install resolve-alpn` should fix the error.

Of course, I should have thought of that 😅. Thanks!
