### ISSUE TITLE
You broke GitHub

### ISSUE THREAD

**Issue by ritave** [szmarczak/http2-wrapper#91]
When I click some of the references in this PR https://github.com/MetaMask/snaps-monorepo/pull/939/files, this error pops-up.

<img width="1144" alt="image" src="https://user-images.githubusercontent.com/1614945/201337117-3f7ae299-f22b-4851-bc15-c60ed1fd23ac.png">

Congratulations!

**Comment by szmarczak** [comment]
LOL. That has to be an older version of `http2-wrapper` since the error doesn't exist in latest. It was meant to handle incorrect usage of listeners:

```
Expected the length of listeners to be 1, got ${i.length}.
Please report this to https://github.com/szmarczak/http2-wrapper/
```

Apparently GitHub thinks this is a definition, what a coincidence 🤣
