### ISSUE TITLE
Examples contain wrong path to load `cert.js` module

### ISSUE THREAD

**Issue by ambujsahu81** [szmarczak/http2-wrapper#93]
Few examples might have wrong paths to load `cert.js` module.
error -> `Error: Cannot find module '../../test/helpers/certs/index.js`.

- https://github.com/szmarczak/http2-wrapper/blob/b55f9f5668e2e57b63daa54bfff4004d75fa63b8/examples/ws/server.js#L4
- https://github.com/szmarczak/http2-wrapper/blob/b55f9f5668e2e57b63daa54bfff4004d75fa63b8/examples/push-stream/server.js#L3

**Comment by szmarczak** [comment]
Indeed! I believe those should go to `certs.js` instead. Would be up to submitting a PR?
