### ISSUE TITLE
HTTP/2 pseudo headers should be converted/dropped when `auto` falls back to HTTP/1

### ISSUE THREAD

**Issue by pimterry** [szmarczak/http2-wrapper#98]
Example:

Www.imdb.com supports HTTP/2. Imdb.com does not, and just uses HTTP/1.1 to return a redirect to the www domain.

Sending the same request using http2-wrapper's `auto` method should work the same for both hosts. Unfortunately, it doesn't:

```javascript
http2.auto({
    hostname: 'imdb.com',
    protocol: 'https:',
    path: '/',
    method: 'GET',
    headers: {
        ':authority': 'imdb.com'
    }
}, (response) => {
    console.log('Got response', response)
}).then(request =>
    request.on('error', (err) => console.log('ERROR:', err)).end()
);
```

This fails, with a `[ERR_INVALID_HTTP_TOKEN]: Header name must be a valid HTTP token [":authority"]` error.

If you do the exact same request but with imdb.com (in the hostname & header) replaced with `www.imdb.com` then it works just fine.

This happens because you _can_ set a custom `:authority` header for HTTP/2 requests, but it's an invalid header for HTTP/1 requests. The HTTP/1 equivalent would be overriding the `host` header. In both cases, it's sometimes useful to set this explicitly (to send the packet to one specific address but independently request content for a different hostname - this can be useful in quite a few cases, e.g. testing a reverse proxy before updating the DNS, or sending requests to a specific IP instead of letting DNS pick the server)

It's difficult to work around this outside http2-wrapper, if you want to set that header, because you can't know which protocol will be used in advance. Fortunately though, it's possible to convert these headers once you do know the protocol, so http2-wrapper could easily do that automatically. The conversion logic is very simple:

* `:authority` -> directly convert into a `host` header (the [relevant bit of RFC](https://httpwg.org/specs/rfc7540.html#HttpRequest) says "an intermediary that converts an HTTP/2 request to HTTP/1.1 MUST create a Host header field if one is not present in a request by copying the value of the :authority pseudo-header field")
* `:method`, `:scheme`, `:path` -> drop it, in HTTP/1 these are specified elsewhere

What do you think @szmarczak?

**Comment by szmarczak** [comment]
Nice find! Looking at the PR right now
